platform :ios, '10.0'
use_frameworks!

target 'Coordinator_Example' do
  pod 'Coordinator', :path => '../'

  target 'Coordinator_Tests' do
    inherit! :search_paths

    pod 'Nimble'
    pod 'Quick'
  end
end
